import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/lib/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-handwriting antialiased`}>
        {/* Wrap children in the Client Provider.
          This enables Smooth Scroll (Lenis) for the whole app 
          without breaking Server Side Rendering.
        */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}